### ISSUE TITLE
Använd gh-pages (kanske)

### ISSUE THREAD

**Issue by perliedman** [dotnetmentor/dotnetmentor.github.io#1]
Om vi gör alla commits till branchen `gh-pages`, så kan vi titta på resultatet direkt från github, vilket kan vara smidigt för debug och visa andra vad som har gjorts.

Men det kanske är något ni redan pratat om?

**Comment by al222cv** [comment]
@perliedman  Hmm låter bra, inte så insatt i GH pages? om man gör commits i den branchen, då kommer de inte ut på http://dotnetmentor.github.io alltså? Utan endast om man commitar till master?

**Comment by perliedman** [comment]
Ah, my bad... tänkte inte på att det var organisationssidan... då är det `master` man skall använda. Så allt är nog som det ska redan!

**Comment by al222cv** [comment]
japp, om man namngav den som dotnetmentor.github.io så verkar det som master funkar :)
